### ISSUE TITLE
Pokedolars como tokens

### ISSUE THREAD

**Issue by danimesq** [Erina-Devs/Bot-Sugerencias#1]
Ningún bot de PS hecho esta función, e las criptomonedas/tokens eren igual la Internet fue en 1995.

Porqué ter los pokedolares como simples números associados a los players (que gastan tiempos y dedicación jugando en el competitivo), cuando pueden ter valor entre multiplos servers y fuera de lo PS?

Empezando el año, yo sugerí la función de tokens para lo PokéHispano; Neon lo gusta la idea, pero dice que no é una prioridade.
Entonces yo pensé más y: para qué una token que solo función en uno server cuando puede también funcionar para otros? Un simples bot puede hacer eso, cambiando las monedas de los pokéservers y enviando tokens que yo puedo gerar utilizando un smart-contract. Mira complexión, pero es simples para implementar en un bot.

Más detalles pueden ser requisitados y yo responderé.

**Comment by nzkdevsaider** [comment]
Archivado y etiquetado en futuros planes de consideración.
